# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RW8yuGWtK1g59RckEBrxv7gjhDLrhkkm
"""

import pandas as pd
a=["prabhu","prasad","venkat","mani","nikhil","kiran","sai"]
r=pd.Series(a,index=[12,13,14,15,16,17,18])
print(r)



import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
print(df.head())
print(df.tail(n=10))

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
print(df.describe)

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
print(df.describe().T)

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
print(df.shape)

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
print(df.columns)
l=list(df.columns)
print(l)

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
l=list(df.columns)
print(l)

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
df2=df.copy()
df2.loc[2:5,'sem1']=None
df2.head(7)

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
df2=df.copy()
df2.loc[2:5,'sem1']=None
df2.isnull().head(7)

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
df2=df.copy()
df2.loc[2:5,'sem1']=None
df2.head(7)
df2.isnull().tail(7)

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
df2=df.copy()
df2.loc[2:5,'sem1']=None
df2.head(7)
print(df['preg'])

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
df2=df.copy()
df2.loc[2:5,'SEM1']=None
df2.isnull().head(7)
print(df2.isnull().sum())

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
print(df[df.index==1])

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
print(df[df.index.isin(range(2,3))])

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
print(df.loc[3])

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
df.loc[6:11]

import pandas as pd
df=pd.read_csv("/content/drive/MyDrive/diabetcsv.csv")
df.loc[6:11,'class']==None
print(df)

df.loc[10:15,['preg','plas']]

df.loc[[10,2,7]]

df.loc[:7,["preg"]]#rows,cloumn

df.loc[df['preg']==6]

df.loc[df['age']>20,['preg']]

df3=df.copy()
df3=df3.dropna()
df3

df3.dropna(inplace=True,axis=1)#inplace says   not to reflect changes inthe df
df3

df3.dropna(inplace=True,how='all')#drops both  rows and columns
df3

mv=df['mass'].mean()
dfn=df.fillna(mv)
print(dfn)
print(mv)

dfn=dfn.drop_duplicates()
print(dfn)

dfn.rename(columns={'class':'group'},inplace=True)
dfn.head()



dfn[['preg','pres']].plot.line()

dfn.groupby('age').min(60)
dfn



